#!/usr/bin/env node
/**
 * Write this package's version into `src/version.ts`.
 *
 * The value reaches every engine as `clientInfo.version` in the `initialize`
 * handshake. It used to be read from the manifest at load time:
 *
 *     createRequire(import.meta.url)('../../package.json').version
 *
 * That is correct for an installed package and wrong for a bundled one. A
 * bundler inlines the module body and rewrites nothing inside the call — the
 * argument is a string handed to a function, not an import specifier, so there
 * is nothing to analyse — and the literal `'../../package.json'` survives into
 * the output chunk, where it now resolves two levels above the consumer's own
 * build directory. A downstream consumer that bundles runskein got
 * `MODULE_NOT_FOUND` while its bundle's top level was still evaluating, before
 * anything it exports was reachable. Where a file does happen to sit at that
 * path, the read succeeds and reports an unrelated package's version to every
 * engine — the worse outcome, because nothing surfaces it.
 *
 * A generated module fixes both: an import specifier is exactly what a bundler
 * does resolve and inline, so the value survives whatever the consumer does
 * with the tree. The manifest stays the one place the version is written; this
 * only copies it, and `--check` is what stops the copy from drifting.
 *
 * Usage:
 *   node scripts/generate-version.mjs            # write src/version.ts
 *   node scripts/generate-version.mjs --check    # fail if it is stale
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const packageRoot = resolve(import.meta.dirname, '..');
const manifestPath = resolve(packageRoot, 'package.json');
const outputPath = resolve(packageRoot, 'src/version.ts');

const { version } = JSON.parse(readFileSync(manifestPath, 'utf8'));
if (typeof version !== 'string' || version === '') {
  console.error('generate-version: package.json has no version to copy');
  process.exit(1);
}

const contents = `// Generated by scripts/generate-version.mjs — do not edit.
// Run \`pnpm --filter @runskein/core generate:version\` after changing the
// manifest version; \`pnpm quality\` fails when the two disagree.

/**
 * This package's version, reported to every engine as \`clientInfo.version\`.
 *
 * A generated constant rather than a manifest read, so that the value survives
 * being bundled into a consumer's own artifact — a runtime path lookup does
 * not. See \`scripts/generate-version.mjs\` for what that cost.
 */
export const CLIENT_VERSION = '${version}';
`;

const current = (() => {
  try {
    return readFileSync(outputPath, 'utf8');
  } catch {
    return undefined;
  }
})();

if (process.argv.includes('--check')) {
  if (current === contents) {
    console.log(`version constant current: ${version}`);
    process.exit(0);
  }
  console.error(
    current === undefined
      ? `src/version.ts is missing; package.json says ${version}.`
      : `src/version.ts does not match package.json (${version}).`,
  );
  console.error('Run `pnpm --filter @runskein/core generate:version` and commit the result.');
  process.exit(1);
}

if (current !== contents) {
  writeFileSync(outputPath, contents);
  console.log(`wrote src/version.ts (${version})`);
} else {
  console.log(`src/version.ts already at ${version}`);
}
