// Generated by scripts/generate-version.mjs — do not edit.
// Run `pnpm --filter @runskein/core generate:version` after changing the
// manifest version; `pnpm quality` fails when the two disagree.

/**
 * This package's version, reported to every engine as `clientInfo.version`.
 *
 * A generated constant rather than a manifest read, so that the value survives
 * being bundled into a consumer's own artifact — a runtime path lookup does
 * not. See `scripts/generate-version.mjs` for what that cost.
 */
export const CLIENT_VERSION = '0.1.0';
